### ISSUE TITLE
Failed deployment for 4.5.4

### ISSUE THREAD

**Issue by TomAugspurger** [dask/helm-chart#127]
https://github.com/dask/helm-chart/runs/1365508373?check_suite_focus=true

```
2020-11-06T20:01:16.4519103Z Cloning into 'dask-4.5.4'...
2020-11-06T20:01:16.6855965Z Warning: Permanently added the RSA host key for IP address '140.82.114.4' to the list of known hosts.
2020-11-06T20:01:17.1387395Z Switched to a new branch 'gh-pages'
2020-11-06T20:01:17.1388251Z Branch 'gh-pages' set up to track remote branch 'gh-pages' from 'origin'.
2020-11-06T20:01:17.1908801Z Successfully packaged chart and saved it to: /tmp/tmpv22n3vhg/dask-4.5.4.tgz
2020-11-06T20:01:17.2658691Z Author identity unknown
2020-11-06T20:01:17.2659456Z 
2020-11-06T20:01:17.2659972Z *** Please tell me who you are.
2020-11-06T20:01:17.2660380Z 
2020-11-06T20:01:17.2660764Z Run
2020-11-06T20:01:17.2661098Z 
2020-11-06T20:01:17.2662248Z   git config --global user.email "you@example.com"
2020-11-06T20:01:17.2663049Z   git config --global user.name "Your Name"
2020-11-06T20:01:17.2663485Z 
2020-11-06T20:01:17.2664116Z to set your account's default identity.
2020-11-06T20:01:17.2664879Z Omit --global to set the identity only in this repository.
2020-11-06T20:01:17.2665282Z 
2020-11-06T20:01:17.2666658Z fatal: empty ident name (for <runner@fv-az195-497.ratd1njd0p4e3f234agjvoye4a.cx.internal.cloudapp.net>) not allowed
2020-11-06T20:01:17.2668014Z $> git log -n 1 --pretty=format:%h -- .
2020-11-06T20:01:17.2668572Z $> git checkout gh-pages
2020-11-06T20:01:17.2669223Z $> helm package dask --destination /tmp/tmpv22n3vhg/
2020-11-06T20:01:17.2670309Z $> helm repo index /tmp/tmpv22n3vhg --url https://helm.dask.org --merge dask-4.5.4/index.yaml
2020-11-06T20:01:17.2670812Z $> git add .
2020-11-06T20:01:17.2671287Z $> git commit -m '[dask] Automatic update for commit 4.5.4'
2020-11-06T20:01:17.3056420Z Traceback (most recent call last):
2020-11-06T20:01:17.3058100Z   File "/opt/hostedtoolcache/Python/3.8.6/x64/bin/chartpress", line 8, in <module>
2020-11-06T20:01:17.3058660Z     sys.exit(main())
2020-11-06T20:01:17.3059939Z   File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/chartpress.py", line 523, in main
2020-11-06T20:01:17.3060571Z     publish_pages(
2020-11-06T20:01:17.3061511Z   File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/chartpress.py", line 398, in publish_pages
2020-11-06T20:01:17.3062446Z     check_call(['git', 'commit', '-m', message], cwd=checkout_dir)
2020-11-06T20:01:17.3063415Z   File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/chartpress.py", line 39, in run_cmd
2020-11-06T20:01:17.3064407Z     return call(cmd, **kwargs)
2020-11-06T20:01:17.3065036Z   File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/subprocess.py", line 364, in check_call
2020-11-06T20:01:17.3065784Z     raise CalledProcessError(retcode, cmd)
2020-11-06T20:01:17.3066987Z subprocess.CalledProcessError: Command '['git', 'commit', '-m', '[dask] Automatic update for commit 4.5.4']' returned non-zero exit status 128.
2020-11-06T20:01:17.3294057Z ##[error]Process completed with exit code 1.
```

**Comment by TomAugspurger** [comment]
Hopefully #128 fixed this.

I'm inclined to just do the push locally, rather than try to delete and re-push the tag through CI.

**Comment by TomAugspurger** [comment]
Pushed 4.5.4 in https://github.com/dask/helm-chart/commit/c30629fc06055fb64729c224293b2a051978821b. Hopefully this doesn't happen next release.

**Comment by jacobtomlinson** [comment]
Thanks for handling this @TomAugspurger
