### ISSUE TITLE
Dask Gateway seems to fail on Dask Hub

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/helm-chart#159]
```yaml
# config.yaml

jupyterhub:
  proxy:
    secretToken: "abc123"
  hub:
    services:
      dask-gateway:
        apiToken: "def456"

dask-gateway:
  gateway:
    auth:
      jupyterhub:
        apiToken: "def456"
```

```
$ helm upgrade --install testcluster dask/daskhub -f config.yaml
Release "rapidshub" does not exist. Installing it now.
...
```

Connecting to the hub and launching a server works fine. 

I noticed the same issue as #131 where the Dask Lab Extension creates `LocalCluster` objects instead of `GatewayCluster` objects.

So I tried to manually create a cluster in Python but got the following error.

```python
>>> from dask_gateway import Gateway
>>> gateway = Gateway()
>>> cluster = gateway.new_cluster()
---------------------------------------------------------------------------
GatewayServerError                        Traceback (most recent call last)
<ipython-input-4-bf15802dc141> in <module>
----> 1 cluster = gateway.new_cluster()

/srv/conda/envs/notebook/lib/python3.8/site-packages/dask_gateway/client.py in new_cluster(self, cluster_options, shutdown_on_close, **kwargs)
    637         cluster : GatewayCluster
    638         """
--> 639         return GatewayCluster(
    640             address=self.address,
    641             proxy_address=self.proxy_address,

/srv/conda/envs/notebook/lib/python3.8/site-packages/dask_gateway/client.py in __init__(self, address, proxy_address, public_address, auth, cluster_options, shutdown_on_close, asynchronous, loop, **kwargs)
    812         **kwargs,
    813     ):
--> 814         self._init_internal(
    815             address=address,
    816             proxy_address=proxy_address,

/srv/conda/envs/notebook/lib/python3.8/site-packages/dask_gateway/client.py in _init_internal(self, address, proxy_address, public_address, auth, cluster_options, cluster_kwargs, shutdown_on_close, asynchronous, loop, name)
    917             self.status = "starting"
    918         if not self.asynchronous:
--> 919             self.gateway.sync(self._start_internal)
    920 
    921     @property

/srv/conda/envs/notebook/lib/python3.8/site-packages/dask_gateway/client.py in sync(self, func, *args, **kwargs)
    341             )
    342             try:
--> 343                 return future.result()
    344             except BaseException:
    345                 future.cancel()

/srv/conda/envs/notebook/lib/python3.8/concurrent/futures/_base.py in result(self, timeout)
    437                 raise CancelledError()
    438             elif self._state == FINISHED:
--> 439                 return self.__get_result()
    440             else:
    441                 raise TimeoutError()

/srv/conda/envs/notebook/lib/python3.8/concurrent/futures/_base.py in __get_result(self)
    386     def __get_result(self):
    387         if self._exception:
--> 388             raise self._exception
    389         else:
    390             return self._result

/srv/conda/envs/notebook/lib/python3.8/site-packages/dask_gateway/client.py in _start_internal(self)
    931             self._start_task = asyncio.ensure_future(self._start_async())
    932         try:
--> 933             await self._start_task
    934         except BaseException:
    935             # On exception, cleanup

/srv/conda/envs/notebook/lib/python3.8/site-packages/dask_gateway/client.py in _start_async(self)
    944         if self.status == "created":
    945             self.status = "starting"
--> 946             self.name = await self.gateway._submit(
    947                 cluster_options=self._cluster_options, **self._cluster_kwargs
    948             )

/srv/conda/envs/notebook/lib/python3.8/site-packages/dask_gateway/client.py in _submit(self, cluster_options, **kwargs)
    533             options = self._config_cluster_options()
    534             options.update(kwargs)
--> 535         resp = await self._request("POST", url, json={"cluster_options": options})
    536         data = await resp.json()
    537         return data["name"]

/srv/conda/envs/notebook/lib/python3.8/site-packages/dask_gateway/client.py in _request(self, method, url, json)
    415                 raise GatewayClusterError(msg)
    416             elif resp.status == 500:
--> 417                 raise GatewayServerError(msg)
    418             else:
    419                 resp.raise_for_status()

GatewayServerError: 500 Internal Server Error

Server got itself in trouble
```

Looking at the Dask Gateway logs it appears it is unable to speak to Jupyter Hub.

```console
$ kubectl logs api-rapidshub-dask-gateway-58f49bcb65-dwt8h        
[I 2021-01-29 11:00:26.631 DaskGateway] Starting dask-gateway-server - version 0.9.0
[I 2021-01-29 11:00:26.823 DaskGateway] Authenticator: 'dask_gateway_server.auth.JupyterHubAuthenticator'
[I 2021-01-29 11:00:26.824 DaskGateway] Backend: 'dask_gateway_server.backends.kubernetes.backend.KubeBackend'
[I 2021-01-29 11:00:26.838 DaskGateway] Dask-Gateway server started
[I 2021-01-29 11:00:26.838 DaskGateway] - Private API server listening at http://:8000
[W 2021-01-29 11:01:30.768 DaskGateway] 401 POST /api/v1/clusters/ 0.862ms
[E 2021-01-29 11:01:30.775 aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 971, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('10.43.212.207', 8081)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/dask_gateway_server/routes.py", line 13, in inner
    return await handler(request)
  File "/usr/local/lib/python3.8/site-packages/dask_gateway_server/routes.py", line 47, in inner
    return await auth.authenticate_and_handle(request, handler)
  File "/usr/local/lib/python3.8/site-packages/dask_gateway_server/auth.py", line 95, in authenticate_and_handle
    user = await self.authenticate(request)
  File "/usr/local/lib/python3.8/site-packages/dask_gateway_server/auth.py", line 389, in authenticate
    resp = await self.session.get(url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 527, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 537, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 894, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1053, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1022, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 977, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 10.43.212.207:8081 ssl:default [Connect call failed ('10.43.212.207', 8081)]
[E 2021-01-29 11:01:30.779 DaskGateway] 500 POST /api/v1/clusters/ 5.383ms
```

**Comment by jacobtomlinson** [comment]
This problem does not happen with `4.5.1`.

**Comment by consideRatio** [comment]
> Looking at the Dask Gateway logs it appears it is unable to speak to Jupyter Hub.

I'm having trouble keeping up with the z2jh/dask-gateway changes being part of various daskhub versions, but that sounds like network policy enforcement for jupyterhub based auth in the daskhub helm chart, which is now fixed. But, perhaps not part of those versions used.

z2jh 0.10 introduced network policy stuff by default
dask-gateway master have the compatibility fix in https://github.com/dask/dask-gateway/pull/352, this is not released as it was merged after 0.9.0 and https://dask.org/dask-gateway-helm-repo/ indicate 0.9.0 is the latest version.
daskhub ??? may have a workaround already by adding a label to the dask-gateway deployment... Hmm no. Then I think at least one issue is because of the combination of z2jh 0.10+ and dask-gateway < 0.9.1 (unreleased).

**Comment by kyprifog** [comment]
Summarizing (I think) we are currently waiting on:  https://github.com/dask/dask-gateway/issues/381
