### ISSUE TITLE
Errors in workers: ModuleNotFoundError: No module named 'joblib'

### ISSUE THREAD

**Issue by jpkli** [dask/helm-chart#50]
I use the following config.yaml to setup my cluster on GKE, but the workers encounter the error: ModuleNotFoundError: No module named 'joblib'. I used both the EXTRA_CONDA_PACKAGES and EXTRA_PIP_PACKAGES to install joblib, but it seems not installed. 

```yaml
worker:
  replicas: 4
  resources:
    limits:
      cpu: 2
      memory: 7.5G
    requests:
      cpu: 2
      memory: 7.5G
  env:
    - name: EXTRA_CONDA_PACKAGES
      value:  joblib numba xarray -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: gcsfs dask-ml numpy pandas sklearn joblib --upgrade

jupyter:
  enabled: true
  env:
    - name: EXTRA_CONDA_PACKAGES
      value:  joblib numba xarray matplotlib -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: gcsfs dask-ml numpy pandas sklearn joblib --upgrade
```

My code for executing with dask: 

```python
from dask.distributed import Client
import joblib

from sklearn.datasets import load_digits
from sklearn.manifold import MDS

# client = Client(processes=False)
client = Client('scheduler-address') 

X, _ = load_digits(return_X_y=True)

with joblib.parallel_backend('dask'):
  embedding = MDS(n_components=2, n_jobs=-1)
  X_transformed = embedding.fit_transform(X[:300])
```

The error I got from the workers: 

```python-traceback
Traceback (most recent call last):
  File "python/test-dask.py", line 14, in <module>
    X_transformed = embedding.fit_transform(X[:300])
  File "/home/kelvin/venv/p36/lib/python3.6/site-packages/sklearn/manifold/mds.py", line 439, in fit_transform
    return_n_iter=True)
  File "/home/kelvin/venv/p36/lib/python3.6/site-packages/sklearn/manifold/mds.py", line 266, in smacof
    for seed in seeds)
  File "/home/kelvin/venv/p36/lib/python3.6/site-packages/joblib/parallel.py", line 1016, in __call__
    self.retrieve()
  File "/home/kelvin/venv/p36/lib/python3.6/site-packages/joblib/parallel.py", line 910, in retrieve
    self._output.extend(job.get())
  File "/home/kelvin/venv/p36/lib/python3.6/site-packages/joblib/_dask.py", line 270, in get
    return ref().result()
  File "/home/kelvin/venv/p36/lib/python3.6/site-packages/distributed/client.py", line 218, in result
    raise exc.with_traceback(tb)
  File "/opt/conda/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 59, in loads
    # The protocol we write by default.  May be less than HIGHEST_PROTOCOL.
ModuleNotFoundError: No module named 'joblib'
```

**Comment by jacobtomlinson** [comment]
Could you share the worker logs? This may highlight whether there was an issue installing the package?

**Comment by consideRatio** [comment]
Hi everyone, I'll close this as stale at this point as it did not receive a response from the author.
