### ISSUE TITLE
Pods won't start from helm chart - Permission denied errors

### ISSUE THREAD

**Issue by kevinpauli** [dask/helm-chart#79]
**What happened**:

I installed the helm chart into a kubernetes cluster (Red Hat Openshift 4.4), but neither the jupyter pod nor the worker pod are starting successfully.

```
% oc version
Client Version: 4.3.3
Server Version: 4.4.8
Kubernetes Version: v1.17.1+3f6f40d
```

```
% helm repo add dask https://helm.dask.org/
% helm repo update
% helm install dask --set worker.replicas=1 dask/dask
```

```
% helm list
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
dask    elo             1               2020-07-14 15:17:42.137373 -0500 CDT    deployed        dask-4.1.12     2.20.0     
```

```
% oc get pods
NAME                              READY   STATUS             RESTARTS   AGE
dask-jupyter-7bb66c97db-cgdjh     0/1     CrashLoopBackOff   3          97s
dask-scheduler-78494dcfc8-bpxxf   1/1     Running            0          97s
dask-worker-584f6fc66c-8kh7n      0/1     CrashLoopBackOff   3          97s
```

Here's the logs of the jupyter pod:
```
% oc logs dask-jupyter-7bb66c97db-cgdjh
+ '[' '' ']'
no environment.yml
+ '[' -e /opt/app/environment.yml ']'
+ echo 'no environment.yml'
+ '[' '' ']'
+ '[' '' ']'
+ exec start.sh jupyter lab
Adding passwd file entry for 1000580000
Container must be run with group "users" to update files
Executing the command: jupyter lab
/opt/conda/lib/python3.8/site-packages/traitlets/config/loader.py:795: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(key) is 1:
/opt/conda/lib/python3.8/site-packages/traitlets/config/loader.py:804: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(key) is 1:
Fail to get yarn configuration. {"type":"error","data":"Could not write file \"/opt/conda/lib/python3.8/site-packages/jupyterlab/yarn-error.log\": \"EACCES: permission denied, open '/opt/conda/lib/python3.8/site-packages/jupyterlab/yarn-error.log'\""}
{"type":"error","data":"An unexpected error occurred: \"EACCES: permission denied, scandir '/home/jovyan/.config/yarn/link'\"."}
{"type":"info","data":"Visit https://yarnpkg.com/en/docs/cli/config for documentation about this command."}

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-lab", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/conda/lib/python3.8/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/notebook/notebookapp.py", line 1766, in initialize
    self.init_configurables()
  File "/opt/conda/lib/python3.8/site-packages/notebook/notebookapp.py", line 1380, in init_configurables
    connection_dir=self.runtime_dir,
  File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/opt/conda/lib/python3.8/site-packages/jupyter_core/application.py", line 100, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/opt/conda/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/jovyan/.local'
```

And here's the log of the worker pod:
```
% oc logs dask-worker-584f6fc66c-8kh7n
no environment.yml
+ '[' '' ']'
+ '[' -e /opt/app/environment.yml ']'
+ echo 'no environment.yml'
+ '[' '' ']'
+ '[' '' ']'
+ exec dask-worker dask-scheduler:8786 --no-dashboard
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.128.0.84:44265'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/site-packages/distributed/process.py", line 191, in _run
    target(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/distributed/worker.py", line 489, in __init__
    os.makedirs(local_directory)
  File "/opt/conda/lib/python3.8/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/dask-worker-space'
distributed.nanny - INFO - Worker process 14 exited with status 1
distributed.nanny - INFO - Closing Nanny at 'tcp://10.128.0.84:44265'
distributed.dask_worker - INFO - End worker
```

**What you expected to happen**:
Dask pods to start succcessfully.

**Comment by kevinpauli** [comment]
Nevermind, it turned out to be an openshift thing.  I was able to fix it by creating a service account with the appropriate security context:

```
oc create serviceaccount runasanyuid
oc adm policy add-scc-to-user anyuid -z runasanyuid --as system:admin
```

and then updating the helm chart to use the service account.

**Comment by jacobtomlinson** [comment]
Glad you found a solution @kevinpauli
